### ISSUE TITLE
Publish this as npm dependency

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#101]
Use cases
* I'm building an examination platform and including qboard would be much easier as a dependency
* I want to share qboards with objects already loaded. Until #4 happens, the only sensible way is using qboard as a dependency (~~currently I manually make a clone of qboard and set pagesJSON~~currently i use #103)

**Comment by pihart** [comment]
Also so that
* when #4 happens, the local/client-only version can be updated simultaneously, without ugly and messy relative imports (or compiler workarounds to hide them)
* it's easier to license them separately if necessary

**Comment by cjquines** [comment]
done https://www.npmjs.com/package/qboard
