### ISSUE TITLE
Fix codeql action

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#107]
~~runs fine on my repo~~

**Comment by cjquines** [comment]
i believe the easiest fix would be removing it!

**Comment by pihart** [comment]
apparently doesn't run fine on my repo anymore. will look into it later

**Comment by pihart** [comment]
It [seems to have been working](https://github.com/cjquines/qboard/actions?query=workflow%3ACodeQL) for a few weeks now

**Comment by pihart** [comment]
FWIW, [typescript's own codeql](https://github.com/microsoft/TypeScript/blob/2e49e286ae7e3cae9587e21238915bc5c854a165/.github/workflows/codeql.yml) is essentially the same thing
