### ISSUE TITLE
Limit context menu to the canvas area

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#110]
Allow right click outside the canvas. Also allow right click on the overlays and modals.

I think the easiest way to do this is just take `e.target` and check against the canvas element before invoking the context menu

**Comment by pihart** [comment]
And of course stop propogationn

**Comment by cjquines** [comment]
janky solution :/ probably morally correct would be to pass in the element itself, but `qboard.baseCanvasElement` and `qboard.canvasElement` arent it

**Comment by pihart** [comment]
native right click still isn't allowed in the non-canvas areas. additionally, #137 seems to negate this issue
