### ISSUE TITLE
Consider removing shelljs dependency

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#112]
I added it in #83 so you can make cross-platform `deploy.js` scripts, but now I'm thinking that maybe this isn't necessary. Because `deploy.js` is explicitly `gitignore`d, any deploy files need to be shared separately, so maybe it makes sense to either rewrite them per platform or commit them to the repo.

Labels:
- question

**Comment by cjquines** [comment]
sgtm

**Comment by pihart** [comment]
Is there any interest in committing the publish (to npm) and deploy (to demo) scripts to the repo?

Example: https://github.com/pihart/ts/tree/master/.github/workflows
Publish be copied identically, docs would become the deploy of the demo, and node.js (CI) can be merged with the existing lint actions. Secrets are not an issue (technically you can even add your deploy scripts as secrets if there's really something to hide).

**Comment by pihart** [comment]
(This would also have us use real versioning and releases, which is an easy, good thing)
