### ISSUE TITLE
Add UI button to request full screen

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#12]
Mobile UI enhancement

**Comment by cjquines** [comment]
im not as sure about this. qboard was not originally intended for mobile, and is not intended for mobile, and so i am iffy about introducing more mobile features. there are lots of good alternatives for drawing apps on your phone. i also dont want a ui button that would go unused on desktop.

**Comment by pihart** [comment]
In that strict sense, you're right, but it's easy to clone it, e.g. at /qboard/mobile or /qboard-mobile, or just encode that the device is in mobile mode (query parameters /qboard?device=mobile or /qboard#mobile). Then link to that site in the bindings modal. I didn't want to focus on that just yet because it's really simple.

**Comment by cjquines** [comment]
i might be willing to merge if you added such a check

**Comment by pihart** [comment]
From a code organization pov, how do you want the toggleFullScreen method to change the toolbar icon and tooltip?

**Comment by cjquines** [comment]
the variable for determining whether we are full screen or not should be in the toolbar itself? if this is for mobile-only, there's no reason to include it as an action, because that'd allow it to be assigned bindings, which doesn't make sense

**Comment by pihart** [comment]
You're right that it shouldn't be an action. The actual boolean for full screen state would be either `!!document.fullscreenElement` or `document.fullscreen`, and changes would be monitored through `fullscreenchange`. (On mobile we don't _really_ need to monitor but we should anyways.)

**Comment by pihart** [comment]
Should I write the mobile UI thing with the assumption that mobile state doesn't change within one page load (true if we use `/qboard/mobile` or `/qboard?device=mobile`; false if we use `/qboard#mobile` or an internal state)?

**Comment by cjquines** [comment]
if the only difference with mobile is going to be the fullscreen button, then i really think it should be internal state

(and again, i am still not convinced that this feature should exist in the first place)

**Comment by pihart** [comment]
I acutally think internal state is the worst of these. If it's an internal state, either there's no direct link to the mobile version, or we store whether the device prefers mobile in localStorage which seems wrong.

(I do store whether the device is mobile in an internal state, after calculating it only once, if that's what you mean)

**Comment by cjquines** [comment]
i think it is fine to not have a link to the mobile version. in fact, i am trying to think of other things a mobile version would have over one that isn’t, and i don’t think i can come up with any? if this is the case then i would be fine just having the button also exist on desktop.

**Comment by cjquines** [comment]
closed by #14
