### ISSUE TITLE
More intuitive help/shortcuts menu shortcut

### ISSUE THREAD

**Issue by chezbgone** [cjquines/qboard#120]
I spent a long time trying to remember that `1` was the key to bring up the list of shortcuts. Maybe use `?` instead (GMail also uses this key to bring up the shortcuts).

**Comment by pihart** [comment]
@cjquines should this be made bindable?

**Comment by pihart** [comment]
I also suggest making the bindings modal show the entire main segment (65%) of the keyboard (potentially excluding the top row). This allows for cross-half (non-symmetric) bindings, makes more keys available, and brings modifiers directly into the UI. The last point also allows for compounding modifiers without complicating the UI.

- [ ] Display full keyboard
- [ ] Remove symmetry
- [ ] Remove modifier row; replace with included keys
- [ ] Make the localStorage format backwards and forwards compatible
- [ ] #114

Should this be a separate issue?

**Comment by cjquines** [comment]
359e36298b2b9ef32113a919df73aa84b1de807f partially resolves.

not sure how youre imagining the new help modal to look like. can you mockup? in particular what would the modifier row look like?
