### ISSUE TITLE
Add shortcut menu to sidebar

### ISSUE THREAD

**Issue by moschindler** [cjquines/qboard#123]
"Press 1 to open or hide this screen" can be easy to miss. Maybe just add a "?" button to the sidebar which opens it?

**Comment by pihart** [comment]
This was suggested once before but now I'm seeing that this can be applied only in non-mobile mode. The full screen button can be removed from non-mobile mode.

The icon would probably be either `info-circle` or `keyboard`, though

**Comment by pihart** [comment]
Resolved with #91 in #140
