### ISSUE TITLE
Add Mobile Mode

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#13]

**Comment by pihart** [comment]
I have a working version using `/qboard?device=mobile`. Should I write the mobile UI thing with the assumption that mobile state doesn't change within one page load (true if we use `/qboard/mobile` or `/qboard?device=mobile`; false if we use `/qboard#mobile` or an internal state)?

_Originally posted by @pihart in https://github.com/cjquines/qboard/issues/12#issuecomment-691571506_

**Comment by cjquines** [comment]
not sure what would be different in a mobile mode other than a full screen button?

**Comment by pihart** [comment]
Potentially small things like tooltips on press instead of hover, maybe add a new horizontal orientation for the Overlay (set as default on mobile?)

**Comment by pihart** [comment]
And if stuff is added to the desktop (a new UI button?) that doesn't make sense on mobile, it would be pretty easy to correct.

**Comment by cjquines** [comment]
closed by #14
