### ISSUE TITLE
Different mechanism for erasing

### ISSUE THREAD

**Issue by califynic** [cjquines/qboard#133]
Seems like the eraser erases anything within the bounding box of any stroke.  This leads to annoying things like the black line being deleted when erasing like this:

![demonstration](https://i.imgur.com/bJLgkLN.png)

It seems like it'd be better to instead only erase if the eraser touches within a certain distance of the actual stroke itself or the like.

Edit: oops looks like this was already mentioned: https://github.com/cjquines/qboard/issues/54 -- somehow I missed this scrolling through the first time around

is there no way to only erase if it touches the actual stroke?

**Comment by cjquines** [comment]
yeah this is in #54 so closing as duplicate. no way to do it; for now an easy fix is to select it with the move tool and then hit delete
