### ISSUE TITLE
copying and pasting groups doesnt work again

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#134]
draw two things with the pen, select both, copy, and paste. it is broken (again)

tested on the deployed versions on my site and avi's ghpages

**Comment by pihart** [comment]
My ghp is currently running https://github.com/pihart/qboard/commit/0564bd8f6419926b74b620d436083b6602c44ef2

**Comment by cjquines** [comment]
works in 9b74838, so it broke somewhere in between idk

**Comment by pihart** [comment]
So oddly it looks like they get added, but just dont render. By adding a new page and going back you can see them.

**Comment by pihart** [comment]
75aacde39a4a2b31e3cb0f9b434e0a3a2321411c is the first bad commit
commit 75aacde39a4a2b31e3cb0f9b434e0a3a2321411c
Author: pihart <avi.mehra1@gmail.com>
Date:   Fri Mar 12 13:46:13 2021 -0800

    Remove unsafe complications from placeObject and caller handleImage

 src/lib/files.ts |  6 +++---
 src/lib/page.ts  | 24 +++++++++---------------
 2 files changed, 12 insertions(+), 18 deletions(-)
