### ISSUE TITLE
tex errors render as black box

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#150]
from #76 

e.g. repro type "x^2" (no wrapping dollars)

**Comment by pihart** [comment]
from https://github.com/cjquines/qboard/issues/76#issuecomment-849408977

> If mathjax doesn't have a builtin way around this then I have no real solution (except for testing whether the image is a black box, which might actually be doable). The reason is, in addition to writing a LaTeX validator, we'd also need to know which environments and commands exist since `\begin{proof}A.\end{proof}` induces the same type of box, and that would be a practically unsolvable problem.
