### ISSUE TITLE
Feature Request - Paste external images in

### ISSUE THREAD

**Issue by PhilipWhiteside** [cjquines/qboard#17]
Paste external images in from clipboard. I often talk about systems talking to other systems, for example. "git talking to github". This request is to be able to paste images, such as the GitHub logo, so that I can draw connectivity/activity/etc between components.

Support for image types that have transparency, such as PNG, would allow them to fit nicely into the board. 
Ability to move and scale the images would allow them to fit into the rest of the content.

**Comment by cjquines** [comment]
yeah, this is #6 , but i think it's important enough that i'll try to impl it next

**Comment by cjquines** [comment]
fixed in 5932e27b376347726861a7be2c73b5a59642319f
