### ISSUE TITLE
undo broken for groups (again)

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#171]
repro: draw two things, select both, move them, undo

**Comment by pihart** [comment]
Bad in b1c90f1e0543683d70010a8131923c2e65ad948b

**Comment by pihart** [comment]
Looks good in 06d7413

**Comment by pihart** [comment]
b9cb04c3dacd951785ce4e94ce0c629c09319ec3 is the first bad commit
commit b9cb04c3dacd951785ce4e94ce0c629c09319ec3
Author: pihart <avi.mehra1@gmail.com>
Date:   Tue Nov 10 16:20:46 2020 -0800

    Don't use private _toObject method

 src/lib/page.ts | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

**Comment by pihart** [comment]
Don't see why this is an issue, though? They look to be doing the same thing:
https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/static_canvas.class.js#L1186-L1199

**Comment by cjquines** [comment]
yeah idk why it doesnt work :/ this was always something i never figured out

**Comment by pihart** [comment]
Oh there's some messy logic here: https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/canvas.class.js#L1262-L1272

**Comment by pihart** [comment]
For now let's revert the commit in #175, and then we can open a new investigative issue
