### ISSUE TITLE
`Reset to default` should probably clear `localStorage.keyMap`

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#172]
Similarly, a fresh page load should not set `localStorage.keyMap`.

The reason is that when we upgrade/change the layout or default bindings (or modify internal names, or implement #114, etc.) , I'd expect that we want default users to use the new default. Any user who particularly likes the default can change this behavior by just setting a binding (and I'm sure most already do, at least to try out different choices), which can be one that's already set to the same value.

**Comment by cjquines** [comment]
agreed
