### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by PhilipWhiteside** [cjquines/qboard#18]
Hey, I've been using your demo for a short while, but since last week it's not been working. I then tried to build this into a Linux container that I could run locally and remove dependence from your demo. However, I have not built a node/react app before. I am comfortable with containers/docker, Linux, etc. The Docker config I do create I will share back to this project. 

Would you be willing to share the deploy steps to stand this up, and I will work on packaging that into a Linux container.

**Comment by cjquines** [comment]
huh, interesting. couldn't get it to work either. i'll investigate and add deploy instructions.

**Comment by cjquines** [comment]
seems to be a server issue. i'm working with my hosting. in the meantime, deploy should just be running `npm run build` in the project folder, does that work?

**Comment by pihart** [comment]
I'm not having any issues with CJ's version but I have a debugger version running at https://pihart.github.io/Chemistry/qboard

**Comment by cjquines** [comment]
yeah, my hosting resolved the issue, closing

**Comment by PhilipWhiteside** [comment]
Thank you for the build command @cjquines it really helped me get the container working. I've submitted a PR #19 with the Dockerfile if you'd like to add that to your project. If not, I'll keep it as a tracking fork.
