### ISSUE TITLE
Retry LaTeX in math mode if text mode errors?

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#185]
If both error, log the error from the first attempt (text mode)

**Comment by cjquines** [comment]
this is weird? i agree it'd be more convenient but like… idk

**Comment by pihart** [comment]
It doesn't really seem too wrong to me. Like naturally I want to write `5x^2` instead of `$5x^2$`, so that's the convienience aspect. I'm not allowed to write this in text mode, though, per MathJax, so qboard should be smart enough to know that I really wanted this to be rendered in math mode. The aspect that makes it not weird to me is that I'm literally not allowed to use `5x^2` in text mode; we only retry in math mode when MathJax fails to render what we ask of it in text mode.

There are cases like this that fail to do precisely what we as users want, but this issue doesn't deal with this case: ![image](https://user-images.githubusercontent.com/18153122/121824311-208d7400-cc60-11eb-918d-e159976fa200.png)


Now granted, #159 would also allow people to default to math mode (but unless you allow them to specify retry options, users can't write both `5x^2` and text directly), though this isn't the same as it's something they must configure themselves.

If qboard gets a native editor as opposed to the browser prompt box, this feature should probably (though not certainly) be removed, because you can just push whatever button to indicate that you want math mode.

And we can be smart about it by only retrying if the error says "... only allowed in math mode"
