### ISSUE TITLE
Pasted images should be size-capped

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#26]
Pasting large or high-res images can completely cover the screen, even on large high-res monitors. Images should be capped by percentage of total screen space, by each dimension independently. Maybe cap at 80% height and 80% width.

**Comment by pihart** [comment]
Applies only to external paste; if an image is intentionally large in qboard and then copied and pasted into qboard, dimensions should remain the same as the original

**Comment by cjquines** [comment]
dont think it should be capped in raw paste; if the computer can handle it we allow it. but think it should be made smaller if it is too large
