### ISSUE TITLE
ui improvements

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#5]
- [x] tooltips for the toolbar
- [x] something that pops up near your cursor when you right click ([as in this](https://medium.com/@subalerts/https-medium-com-implementing-custom-context-menu-in-react-js-part-1-b103260c724c))
- [x] add other keyboard layouts
- [x] add right-handed keybindings

**Comment by cjquines** [comment]
sameer had some good suggestions for rh keybindings

**Comment by cjquines** [comment]
tooltips closed by 085d8705e1cd045639329eb73d52207e90cd85b1
left-handed keybindings closed by 822c2704945b369b1820d192d27817452fcf42d6
need to test if `1` as help key works in practice, otherwise switch to mirroring g / h

**Comment by cjquines** [comment]
need to align left-handed keyboard keys properly; on most keyboards YHN are in the opposite diagonal direction

**Comment by pihart** [comment]
- [ ] 2-finger rotate?

**Comment by pihart** [comment]
- [ ] When an object is selected, changing styles also changes the styles of the object?

**Comment by cjquines** [comment]
> * [ ]  When an object is selected, changing styles also changes the styles of the object?

already in #6

**Comment by cjquines** [comment]
context menu from 58fff965b796c2586eb3ddfa5cdd5bc030c95ded

this closes the issue; @pihart if you want 2-finger rotate you can reopen one
