### ISSUE TITLE
Undo-redo for images isn't guaranteed

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#61]
Paste an image (clipboard, or upload from input in latest commit) and do undo-redo. After some number of iterations (usually first), image will not appear. Continue to do it; eventually it will reappear.

Issue is at least as old as 816493ca441995986651f2596678f606a9a061ab and occurs on CJ's demo too.
(@cjquines please put the commit hash as a comment in the hosted html file)

**Comment by cjquines** [comment]
no idea what the demo's commit is, but i think it's later than the commit you mention.

i've never experienced this issue despite undoing and redoing several times, nor could i reproduce it? my first guess would be that the image's file url is being invalidated, but i'm not sure if that's why?

**Comment by cjquines** [comment]
okay, can reproduce. my guess is that it's not rendering all after redoing. am investigating.
