### ISSUE TITLE
import/export from json

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#7]
title

**Comment by pihart** [comment]
Should it preserve history or should "load from JSON" be a single history event

**Comment by cjquines** [comment]
dont think preserving history is worth it?

**Comment by cjquines** [comment]
todo: expose this in the ui

i still disagree with this being in history. in fact, i dont think importing json should append pages, but rather, replace the entire document; it should be analogous to opening and saving a file ui-wise. i also don't really see a usecase for this; qboard was never intended to work with multiple documents, and was always supposed to be for presentations (and i guess, now, scratch work). so i'm not sure if i'll keep the splicing pages thing

**Comment by pihart** [comment]
One thing I wanted to add was a check to see if the open document is new (as in the union the pages contains no objects), and in that case, don't append but overwrite.

**Comment by cjquines** [comment]
resolved through #21 and 715609841b65ab13e5ad97b01d3a54e97eff4c33
