### ISSUE TITLE
It lost one of my pages

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#72]
Page numbers k and k+1 both got rendered as what should've been page k + 1's content. When exported as JSON, obj.pages[k - 1] and obj.pages[k] are identical, so the content was lost. Same when exporting as PDF, so I think internally pagesJSON was incorrectly modified due to a race condition. (Page number k was a very large page in terms of bezier curves so maybe that's why.)

Not sure how to reproduce.

**Comment by cjquines** [comment]
closing as old and unable to reproduce

**Comment by pihart** [comment]
wait don't close. mark as stale

**Comment by cjquines** [comment]
this has been stale for. two months. this is fine

**Comment by pihart** [comment]
can you label as unresolved or something for reference?

**Comment by pihart** [comment]
^
