### ISSUE TITLE
exported pdfs don't have pictures

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#75]

**Comment by pihart** [comment]
yikes

**Comment by cjquines** [comment]
yeah its incredibly yikes

**Comment by pihart** [comment]
They don't get saved to JSON either. The reason is simple. See this export:
```json
{"qboard-version":1,"pages":[{"version":"4.2.0","objects":[{"type":"image","version":"4.2.0","originX":"center","originY":"center","left":583.15,"top":581.96,"width":218,"height":80,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"cropX":0,"cropY":0,"id":1,"strokeUniform":false,"src":"blob:https://pihart.github.io/9d963524-c115-487a-b0eb-96ae3f1fa6d9","crossOrigin":null,"filters":[]}],"background":"white"}]}
```
The images get saved as blob urls which means something like `canvas.toDatalessJSON` is being called internally somewhere.

**Comment by pihart** [comment]
Actually, I think fabric doesn't update the url after you do `fabric.Image.fromURL`

**Comment by cjquines** [comment]
we can override the toJSON method or something of the object to embed the image too? or i think just replacing toDatalessJSON with just toJSON or whatever it was called should fix this

**Comment by pihart** [comment]
No, I think the issue might be different. I don't know fabric very well, but I think you have to do something else when creating an image from a blob url.

**Comment by pihart** [comment]
A temporary fix would be to store an array of the blob urls and the actual image data; then add that in the json at save-to-json time. When opening, the json file, so a search and replace against that array and create a new blob.
