### ISSUE TITLE
Warning on changing URL/page

### ISSUE THREAD

**Issue by PhilipWhiteside** [cjquines/qboard#81]
I've accidentally navigated away from the page, losing all my content, more times than I'd like to admit. This is completely human error, but could be sorted in software. When I click the back button on my mouse I got back to the new tab page, it's right where my thumb sits, so accidental taps are common. If I use my pen this isn't a problem but sometimes I switch to a GUI of something to show rather than whiteboard. 

I've seen sites that are active have a pop up "are you sure" box. Simple yes or not to allow or stop.

**Comment by pihart** [comment]
I added this in #34. It works in both [my demo](https://pihart.github.io/qboard) and [cj's](https://pihart.github.io/qboard).

It should give the dialog if and only if both of the following:
- The document is not blank in that it has at least one object
- The document has been modified after either
  - Opening a document from JSON
  - Saving the document to JSON
