### ISSUE TITLE
Re-expose mobile mode in the UI

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#91]
Keep all the logic and keep user preference in localStorage, but don't allow people to switch anymore. Use mobile mode internally no matter what.

Reason: we still have that the only thing different in mobile mode is the full screen button. Just leave the button exposed for everyone, at least until the changes in mobile mode are implemented.

**Comment by cjquines** [comment]
now that 359e36298b2b9ef32113a919df73aa84b1de807f shows shortcut menu in sidebar (see #123 ) we should re expose it. idk what the morally correct way to revert #131 is though

**Comment by pihart** [comment]
Is the idea to have the button be `help` on desktop and `full screen` on mobile? This doesn't seem right—both of these buttons should be available on mobile.

Regardless, it looks like https://github.com/pihart/qboard/commit/60fb23537cbe42d889d3676e12bf6b779784b399 is the right way to revert.

**Comment by cjquines** [comment]
oh yeah. hm. they should both be available on mobile, yeah
