### ISSUE TITLE
Option to insert at page 0

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#92]
Either reduce the count to be ![-n, \dots, -1, 0] (extend in the negative direction; I don't like this) or insert a page at position 0 in the array.

Maybe this shouldn't be the default behavior and maybe the command to enable this behavior shouldn't be exposed in the UI, but I still find this useful. Right now the best workarounds are
* inserting a page *after* the first page (sometimes I begin work on the second page for this reason) through the JSON drops (I have a blank page JSON file I drop)
* exporting to JSON, manually editing it, and then re-importing
* exporting to JSON, opening a blank qboard, and dropping the exported JSON

[-n, \dots, -1, 0]: https://render.githubusercontent.com/render/math?math=-n,\dots,-1,0&mode=inline

**Comment by cjquines** [comment]
closing as old. probably want to figure out a way to add a page at 0 instead.

**Comment by pihart** [comment]
well yeah, that's what this issue is. i changed the title in accordance.

it's solely a ui thing, so i'm leaving it for you. one possible way is putting this behavior into the previous page button of page 0.

**Comment by cjquines** [comment]
i think that's a good idea. maybe make the previous page a plus sign when at page 1?
