### ISSUE TITLE
Undoing delete of an object lifts it to the top

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#96]
This should not be the behavior. Don't know if there's a clean way to handle this though, since undo/redo creates a clone object

**Comment by cjquines** [comment]
can we git bisect this to figure out when this happened

**Comment by pihart** [comment]
I'm assuming this has always been the case because I can't think of any reasonable solution

**Comment by cjquines** [comment]
i don tthink this was always the case?

**Comment by pihart** [comment]
Well, hasn't redo always been
```js
this.canvas.apply(item.ids, item.oldObjects); 
```
and then add is supposed to add object.

Because that's how it is now, and it seems thats the reason why: you're regenerating the objects from history.
https://github.com/cjquines/qboard/blob/4858b37564cf1392f0afe214d1cce8a0e4384533/src/lib/history.ts#L98
https://github.com/cjquines/qboard/blob/4858b37564cf1392f0afe214d1cce8a0e4384533/src/lib/page.ts#L73-L90

**Comment by pihart** [comment]
Relevant code (logical component) is nearly identical to before I started working on qboard.
https://github.com/cjquines/qboard/compare/71bfd29c6b7432d9dba37e623054084e76dab2ed...4858b37564cf1392f0afe214d1cce8a0e4384533

Only the apply method changed

**Comment by cjquines** [comment]
okay. might be the same bug as make two rectangles, select both, copy, paste, undo, redo. investigating

**Comment by pihart** [comment]
This has not been resolves as of 3a2159991649156535d0f8b0109179aa845fab8b

**Comment by pihart** [comment]
This is still an issue as of e8e8f15240b286179786203ae768fa34b185aed4 and eb3b630b754eb5e3f107909a160ef47d97b20ebd.

Can this be reopened?

**Comment by pihart** [comment]
Still an issue at present
